# -*- coding: utf-8 -*-
"""ACTIVIDAD 6 Sauri Luna.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tixOXHKzH_TiVg10I0rAyS_vw44wp_XC

#ACTIVIDAD N°6 Cuenta

Crea una clase llamada Cuenta que tendrá los siguientes atributos: titular (que es una persona) y cantidad (puede tener decimales). El titular será obligatorio y la cantidad es opcional. Construye los siguientes métodos para la clase: 

 Un constructor.
 mostrar(): Muestra los datos de la cuenta. 
 ingresar(cantidad): se ingresa una cantidad a la cuenta, si la cantidad introducida es negativa, no se hará nada. 
 retirar(cantidad): se retira una cantidad a la cuenta. La cuenta puede estar en números rojos
"""

class Cuenta:
    def __init__(self, titular="Luna", cantidad=2.5):
        self.titular = titular
        self.cantidad = cantidad
        
    def mostrar(self):
        print("Titular:", self.titular)
        print("Cantidad: $", self.cantidad)
        
    def ingresar(self, cantidad):
        self.cantidad += cantidad
        print("Se ingresaron $", cantidad, "en total tenés $",self.cantidad)
        
    def retirar(self, cantidad):
        self.cantidad -= cantidad
        print("Se retiraron $", cantidad, "el saldo total es $",self.cantidad)
        

cuenta1=Cuenta("Faku", 1500.22)

cuenta1.mostrar()

print("----------------------------------------------------------------------")

cuenta1.ingresar(2400)

print("----------------------------------------------------------------------")

cuenta1.retirar(200.33)